### ISSUE TITLE
#01 Get enquiry details by id

### ISSUE THREAD

**Issue by KudaleAparna** [narkhedepratik/ApnaFainanceRest#10]
-[ ] In com.health.main.controller.EnquiryController class write one get api to get particular (single) enquiry details , 
       endpoint of this API should be as '/enquiry/GetById/{id}'
-[ ] Create the required service method in existing classes and Interfaces.

**Comment by Swatibharti01** [comment]
Get Enquiry Details By Id Code Completed.
