### ISSUE TITLE
#04 Post API for customer

### ISSUE THREAD

**Issue by KudaleAparna** [narkhedepratik/ApnaFainanceRest#13]
-[] Write multipart API to post customer Information
- [] Create com.health.main.model.Customer class and declare the below mention properties
- [] Create com.health.main.controller.CustomerController and get '/customer' as RequestMapping. Write post API as '/customer/create_customer' and store customer object in customer database.
- [] To store customer object create Required service as below
- [] com.health.main.service.CustomerService(Interface)
- [] com.health.main.serviceImpl.CustomerServiceImpl(class)
- []Create Repository for customer as com.health.main.repository.customerRepository

**Comment by NileshAkhadkar** [comment]
Post API for customer  completed
