### ISSUE TITLE
#09 Post API for Enquiry

### ISSUE THREAD

**Issue by KudaleAparna** [narkhedepratik/ApnaFainanceRest#18]
-[] Create com.health.main.controller.CustomerEmailController and write one API to send email on register emailId of an enquiry form,regarding authentication details of an enquiry, endpoints of this API should be  as '/mail/auth_mail/{customerId}'
-[] Create com.health.main.service.mailService(I) and write one abstract method as sendAuthMail(int customerId)
-[] Create com.health.main.serviceImpl.MailServiceImpl(c) and Implement MailService(I) and override sendAuthMailMessage
-[] Create one utility class as com.health.main.CustomerMailUtility and write down utility method to send email

**Comment by Harshawk13** [comment]
#9 Enquiry cibil details mail


![Screenshot (207)](https://github.com/narkhedepratik/ApnaFainanceRest/assets/155630258/1842600f-4a6d-4f6a-9330-840479798570)
