### ISSUE TITLE
#01 Employee Auth details mail

### ISSUE THREAD

**Issue by narkhedepratik** [narkhedepratik/ApnaFainanceRest#2]
- [x] create com.health.main.controller.EmailController and write one api to send email on register emailId of an employee, regarding authentication details of perticular employee, the endpoint of this api should be as '/mail/auth_mail/{employeeId}'.
- [x]  Create com.health.main.service.MailService(I) and write once abstract method as sendAuthMail(int employeeId);
- [x]  Create com.health.main.serviceimpl.MailServiceImpl(C) and implement MailService (I) and override sendAuthMailMessage.
- [x]  Create One utility class as com.health.main.EmailUtility and write down the utility method to send email.
- [x]    Also add the required  dependancy and configuration.

**Comment by Harshawk13** [comment]
Task has been completed
