### ISSUE TITLE
#04 Post API for LoanDisbursement

### ISSUE THREAD

**Issue by KudaleAparna** [narkhedepratik/ApnaFainanceRest#22]
create com.health.main.controller.LoanDisbursement and write the post api as '/create_LoanDisbursement' get the request body in api paramerter and store the LoanDisbursement details in database.
to store LoanDisbursement object create required service as below.
com.health.main.service.LoanDisbursement(Interface)
com.health.main.serviceimpl.LoanDisbursement(Class)

**Comment by mrfaizanpatel** [comment]
post api done
