### ISSUE TITLE
#02 Get all employees

### ISSUE THREAD

**Issue by narkhedepratik** [narkhedepratik/ApnaFainanceRest#3]
- [ ] create one get api to expose all employee details of the database. (use existing classes and interface of employee)

**Comment by Swatibharti01** [comment]
![code](https://github.com/narkhedepratik/ApnaFainanceRest/assets/156159025/1c4ec017-e27f-45f1-bd1c-3f8c2f16698f)

GetAllEmployees Task Completed..
