### ISSUE TITLE
#03 Login Authentication

### ISSUE THREAD

**Issue by narkhedepratik** [narkhedepratik/ApnaFainanceRest#4]
- [x] Write on get api for login authentication of employee in EmployeeController as '/employee/login/{username/{password}'
-[ ] extract the pathveriables from uri and authenticate user.
-[ ] to authenticate the employee create one abstract method in EmployeeService as   'Employee   logincheck(String username ,String password);
- [x] In EmployeeServiceImpl implement the logincheck method and if username or password is not valid throw custom exception InvalidAuthDetails.
- [x]  create custom exception class as com.health.main.exception. InvalidAuthDetails.
- [x]  Create One class to handle exceptions of an application as com.health.main.rest_exception.ApplicationExceptionHandler annotate this class with @RestControllerAdvoice annotation and write down the method to handle InvalidAuthDetailsException.

**Comment by NileshAkhadkar** [comment]
Login authentication code completed.
