### ISSUE TITLE
#06 Delete Api for employee

### ISSUE THREAD

**Issue by narkhedepratik** [narkhedepratik/ApnaFainanceRest#7]
-[ ] in com.health.main.controller.EmployeeController class write one get api to delete particular (single) employee details, endpoint of this api should be as '/employee/employee/{id}'
-[ ] create the required service method in existing classes and interfaces.

**Comment by mrfaizanpatel** [comment]
The delete api is completed

endpoint url:- 'http://localhost:9091/employee/delete/2'
