### ISSUE TITLE
#07 Post Enquiery

### ISSUE THREAD

**Issue by narkhedepratik** [narkhedepratik/ApnaFainanceRest#8]
-[ ] create the required entities in 'com.health.main.model' package mainly Enquiry andCilbil as method below
 <html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/prati/AppData/Local/Packages/oice_16_974fa576_32c1d314_3ff0/AC/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/prati/AppData/Local/Packages/oice_16_974fa576_32c1d314_3ff0/AC/Temp/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Enquiry |   |  
-- | -- | --
Fields | Data Type | Relationship
customerID | Interger |  
firstName | String |  
lastName | String |  
age | Interger |  
email | String |  
mobileNo | Double |  
pancardNo | Double |  
cibilSCore | Cibil | oneToOne
  |   |  
Cibil |   |  
Fields | Data Type | Relationship
cibilId | Interger |  
cibilScore | Interger |  
cibilScoreDateTime | String |  
status | String |  

</body>

</html>

- [ ] Create EnquireyController class in 'com.health.main.controller' package and write down on post api for enquiry , the endpoint of this api should be '/enquiry/create_enquiry'
- [ ]  Create com.health.main.service.EnquiryService and add required service mehtod to save enquiry.
- [ ]  Create com.health.main.serviceimpl.EnquiryServiceImpl  and implement EnquiryService (I);
- [ ]  Create com.health.main.repository.EnquiryRepository for enquiry.

**Comment by narkhedepratik** [comment]
Do it on priority

**Comment by Aarti1505** [comment]
Task has been done

**Comment by narkhedepratik** [comment]
Ok
