### ISSUE TITLE
#08 Get all enquiry

### ISSUE THREAD

**Issue by narkhedepratik** [narkhedepratik/ApnaFainanceRest#9]
-[ ] write one get api to expose all enquiries in EnquiryController endpoint should be as '/enquiry/enquiries'
-[ ] create required service method in existing classes and interfaces.

**Comment by Monikap17** [comment]
Get All Enquiry Details Task Completed..
[Doc1.docx](https://github.com/narkhedepratik/ApnaFainanceRest/files/13890891/Doc1.docx)
